In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import AveragePooling2D


In [7]:
image = np.array([[2,2,7,3],
                 [9,4,6,1],
                  [8,5,2,4],
                  [3,1,2,6]])
image=image.astype("float32")

In [8]:
image = image.reshape(1,4,4,1)

In [9]:
model = Sequential([AveragePooling2D(pool_size = 2, strides =2)])

In [14]:
output = model.predict(image)
print(output)

1/1 [==============================] - 0s 20ms/step
[[[[4.25]
   [4.25]]

  [[4.25]
   [3.5 ]]]]


In [15]:
output = np.squeeze(output)
print(output)

[[4.25 4.25]
 [4.25 3.5 ]]
